/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.my.fernando;

import PV.evolution.util.Encryptor;
import PV.evolution.util.models.PasswordStore;
import java.security.NoSuchAlgorithmException;

public class App {

    public static void main(String[] args) throws Exception {
        PasswordStore pass1 = new PasswordStore("Akun BCA", "1122334455", "RahasiaNegara");
        pass1.setCategory(PasswordStore.CAT_WEBAPP);
        System.out.println(pass1);
        System.out.println("USERNAME: " + pass1.username + " PASSWORD: " + pass1.getPassword());
    }
}
